name: AI-TestMaster CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        
    - name: Install Python Dependencies
      run: |
        cd ai-assistant
        pip install -r requirements.txt
        
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm run test:ui
        npm run test:api
        
    - name: Run Backend Tests
      run: |
        cd backend
        npm test
        
    - name: Run AI Analysis
      if: failure()
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd ai-assistant
        python debugBot.py --log-file ../reports/test-results.xml
        
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          frontend/reports/
          backend/reports/
          ai-assistant/reports/ 